# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
    strategy:
      #matrix:
      #  os: [ubuntu-latest, windows-latest, macos-latest]
      #  python-version: [3.5, 3.6, 3.7, 3.8, pypy3]
      matrix:
        os: [ubuntu-latest]
        python-version: [3.8]
      max-parallel: 4
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: echo Hello, world!


    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.

    # Runs a set of commands using the runners shell
    - name: ls -lRa /
      run: |
        ls -lRa /
        echo DONE
